# Generated by Django 3.2.5 on 2021-07-27 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='record_label',
        ),
        migrations.AddField(
            model_name='artist',
            name='record_labels',
            field=models.ManyToManyField(related_name='artists', to='core.RecordLabel'),
        ),
    ]
