# Generated by Django 3.2.5 on 2021-07-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210727_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='record_labels',
        ),
        migrations.AddField(
            model_name='artist',
            name='record_label',
            field=models.CharField(default='Shady Records', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Ten')]),
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='RecordLabel',
        ),
    ]
